// Generated by CoffeeScript 1.6.3
(function() {
  var OffCanvasToggle;

  $(function() {
    var size;
    size = window.getComputedStyle(document.body, ':after').getPropertyValue('content');
    if (size === 'mobile') {
      $('body').addClass('mobile');
      return console.log('mobile');
    }
  });

  OffCanvasToggle = {
    init: function(triggers) {
      return $(triggers).click(function(e) {
        console.log('wat');
        e.preventDefault();
        return OffCanvasToggle.toggleClasses(this);
      });
    },
    toggleClasses: function(el) {
      var body, direction;
      body = $('body');
      direction = $(el).attr('href');
      if (direction === '#left') {
        body.toggleClass('show-left').removeClass('show-right');
      }
      if (direction === '#right') {
        body.toggleClass('show-right').removeClass('show-left');
      }
      return body.attr('class');
    },
    toggleText: function(triggers) {
      var body, left, right;
      body = $('body');
      left = $(triggers).filter('[href="#left"]');
      right = $(triggers).filter('[href="#right"]');
      if (body.hasClass('show-left')) {
        left.text('hide left');
      } else {
        left.text('show left');
      }
      if (body.hasClass('show-right')) {
        return right.text('hide right');
      } else {
        return right.text('show right');
      }
    }
  };

  $(document).ready(function() {
    return OffCanvasToggle.init($('.toggle'));
  });

  $(document).ready(function() {
    $('.header > .site-logotype').fitText(1.2);
    return $('.scroll-target').smoothScroll();
  });

}).call(this);
