// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $.getJSON("https://gdata.youtube.com/feeds/api/users/bryanveloso/uploads?v=2&max-results=1&alt=jsonc", function(response) {
      return console.log(response.data.items[0]);
    });
    $.getJSON("https://gdata.youtube.com/feeds/api/users/bryanveloso?v=2&alt=json", function(response) {
      return $('.js-youtube-subscriber-count').text(response.entry.yt$statistics.subscriberCount);
    });
    return $.getJSON("https://gdata.youtube.com/feeds/api/playlists/PLD47E8E769D01C633?v=2&alt=jsonc", function(response) {
      var video;
      video = response.data.items[0].video;
      return console.log(video);
    });
  });

}).call(this);
